# 本地PV创建
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq
  labels:
    pv: rabbitmq
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /home/wendi/workspace/nfs
    server: 192.168.1.102



---
#创建声明PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-rabbitmq-volume
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      pv: rabbitmq
---