---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 15672
    name: http
    protocol: TCP
    nodePort: 15672
  - port: 5672
    name: amqp
    protocol: TCP
    nodePort: 5672
  - port: 25672
    name: clustering
    protocol: TCP 
  selector:
    app: rabbitmq
  type: NodePort



---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: http
  selector:
    app: rabbitmq



---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: rabbitmq
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: rabbitmq
        image: zhangwendi/rabbitmq:3.6.14
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: http
        env: 
        - name: RABBITMQ_ERLANG_COOKIE
          value: UeCinu9N8FmL6Z/z8OOqGDU1MZT9VyRFHBDJJUdQrK4=
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_SERVICE_NAME
          value: "rabbitmq"
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: RABBITMQ_NODENAME
          value: "rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME)"
        - name: RABBITMQ_DEFAULT_USER
          value: admin                        # 连接rabbit的账号
        - name: RABBITMQ_DEFAULT_PASS
          value: admin                       #连接rabbit的密码
        - name: RABBITMQ_DEFAULT_VHOST      # vhost
          value: vhost
        - name: RABBITMQ_NODE_TYPE        # 持久化到磁盘
          value: disc
        - name: AUTOCLUSTER_TYPE
          value: "k8s"
        - name: AUTOCLUSTER_DELAY
          value: "2"
        - name: AUTOCLUSTER_CLEANUP
          value: "true"
        - name: CLEANUP_WARN_ONLY
          value: "false"
        - name: K8S_ADDRESS_TYPE
          value: "hostname"
        - name: K8S_HOSTNAME_SUFFIX
          value: ".$(K8S_SERVICE_NAME)"
        volumeMounts:
        - name: rabbitmq-volume
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-volume
        persistentVolumeClaim:
          claimName: dev-rabbitmq-volume